#include "heap.h"
#include "integer.h"
#include <stdio.h>

int main(void) {
    HEAP *h = newHEAP(displayINTEGER, rcompareINTEGER, freeINTEGER);
    insertHEAP(h, newINTEGER(3));
    insertHEAP(h, newINTEGER(-2));
    insertHEAP(h, newINTEGER(-5));
    insertHEAP(h, newINTEGER(-3));
    insertHEAP(h, newINTEGER(1));
    insertHEAP(h, newINTEGER(-3));
    insertHEAP(h, newINTEGER(-2));
    insertHEAP(h, newINTEGER(-5));
    insertHEAP(h, newINTEGER(4));
    insertHEAP(h, newINTEGER(5));
    insertHEAP(h, newINTEGER(2));
    insertHEAP(h, newINTEGER(-3));
    insertHEAP(h, newINTEGER(-1));
    buildHEAP(h);
    displayHEAPdebug(h, stdout);
    void *extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);
    extracted = extractHEAP(h);
    printf("extracted: ");
    displayINTEGER(extracted, stdout);
    printf("\n");
    displayHEAPdebug(h, stdout);

    return 0;
}
